### ISSUE TITLE
Intergration not loading

### ISSUE THREAD

**Issue by davy932** [helto4real/custom_component_myfitnesspal#11] opened 2021-11-22 16:07 UTC
Hi,
I got the custom component to load via HACS.  It is visible on the intergration page but spools and does not load or allow you to enter any of your account details.

**Comment by helto4real** [comment] 2021-11-23 19:53
Thanks for reporting, will check it our.

**Comment by helto4real** [comment] 2021-11-23 20:15
I can add if fine. Try to remove and re-add the integration

**Comment by lasharor** [comment] 2022-01-21 15:20
Same is happening for me,

Can install. But when selected via integration page it will not load the config flow.

**Comment by helto4real** [comment] 2022-01-30 19:08
I think this is fixed in the new version. Can you test and close issue if so @lasharor ?

**Comment by davy932** [comment] 2022-01-30 22:47
I only get one entity - I percentage value. 

Should I expect more 

Regards

David Evans
+353 87 2938629

On 30 Jan 2022, at 19:09, Tomas Hellström ***@***.***> wrote:

﻿
I think this is fixed in the new version. Can you test and close issue if so @lasharor ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lasharor** [comment] 2022-01-31 07:06
@davy932 Yes, Only one entity. The entity contains attributes with all of the relevant info. 

@helto4real I can't close this. You or davy should close the issue.

**Comment by helto4real** [comment] 2022-01-31 14:19
Yes it is by design it is one entity check the attributes for more info.

**Closed as completed by helto4real** 2022-01-31 14:19 UTC
