### ISSUE TITLE
Retrying setup: None

### ISSUE THREAD

**Issue by chris-github1975** [helto4real/custom_component_myfitnesspal#16] opened 2022-02-09 21:21 UTC
After adding the integration i see this error on screen.
Logs show....
Logger: custom_components.my_fitnesspal
Source: helpers/update_coordinator.py:219
Integration: myfitnesspal ([documentation](https://github.com/helto4real/custom_component_myfitnesspal))
First occurred: 20:29:26 (15 occurrences)
Last logged: 20:43:05

Error fetching my_fitnesspal data: 'dictionary is empty'

Currently using the latest Home Assistant version, 2022.2.5

**Comment by iotemylabs** [comment] 2022-02-16 18:21
+1, mine as well, also not working in 2022.2.7 of Home Assistant

**Comment by helto4real** [comment] 2022-02-19 14:57
Is this still a problem with the current version? @chris-github1975  @iotemylabs ? I cannot  reproduce it.
I use the `v0.11a` version of the integration and `2022.2.9`

**Comment by chris-github1975** [comment] 2022-02-20 15:01
Hi
I've just tried reinstalling again, and yes, it still doesn't work for me.
![image](https://user-images.githubusercontent.com/59799554/154848818-7e855613-d4e2-4b7a-b624-f3d0aa20a81d.png)
![image](https://user-images.githubusercontent.com/59799554/154848926-2dea8eef-f741-4f9f-9e15-ef7b8dd06c54.png)

I was wondering if you needed to have the paid version of fitnesspal for this to work ? I'm on the free level.

**Comment by helto4real** [comment] 2022-02-20 15:47
I have the free level too. This is weird hmmm. I tried now with a completely fresh install using my email and password. No errors. Sadly cannot reproduce this. Did you pass a name too? I wonder. A recent change was to use weight as sensor. If it is not available. Can I ask if you use weight? If not try to add an weight att try again?

**Comment by chris-github1975** [comment] 2022-02-20 16:30
I've just created a brand new fitnesspal account and it works. I wonder if there is something either in one of my settings or some difference with accounts created past a certain time. I've had my account for many years.

**Comment by helto4real** [comment] 2022-02-20 16:46
Ok I am releasing a "fix" for some other issue that use only "lb" as weight meassure. Now use the configured HA value. I also did a check for weight exists. That might help.

**Comment by helto4real** [comment] 2022-02-20 16:48
Now it is released. Please try that version to see if it works

**Comment by chris-github1975** [comment] 2022-02-20 17:04
Unfortunately the error is still the same.

**Comment by helto4real** [comment] 2022-02-20 17:25
Ok thanks for reporting back. Hmm I will investigate further. Can you please look at the raw logs. "LOAD FULL HOMEASSISTANT LOGS". It might show the row where the error occurs

**Comment by chris-github1975** [comment] 2022-02-20 18:17
I changed logging to 'debug' but not much was shown.

2022-02-20 18:06:17 ERROR (MainThread) [custom_components.my_fitnesspal] Error fetching my_fitnesspal data: 'dictionary is empty'
2022-02-20 18:06:17 DEBUG (MainThread) [custom_components.my_fitnesspal] Finished fetching my_fitnesspal data in 3.288 seconds (success: False)
2022-02-20 18:06:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'chris' for my_fitnesspal integration not ready yet: None; Retrying in background

I have tried changing all sorts of settings in my fitnesspal account but to no avail.

If you would like to debug further I am willing to give you my username and password to test with ?
I can always use a newly created account as I'm not bothered about all my history.

**Comment by helto4real** [comment] 2022-02-20 18:52
> I changed logging to 'debug' but not much was shown.
> 
> 2022-02-20 18:06:17 ERROR (MainThread) [custom_components.my_fitnesspal] Error fetching my_fitnesspal data: 'dictionary is empty' 2022-02-20 18:06:17 DEBUG (MainThread) [custom_components.my_fitnesspal] Finished fetching my_fitnesspal data in 3.288 seconds (success: False) 2022-02-20 18:06:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'chris' for my_fitnesspal integration not ready yet: None; Retrying in background
> 
> I have tried changing all sorts of settings in my fitnesspal account but to no avail.
> 
> If you would like to debug further I am willing to give you my username and password to test with ? I can always use a newly created account as I'm not bothered about all my history.

That would be great! Thanks! If you have discord my user is helto#3598 find me there and we exchange the information. Thanks alot!

**Comment by iotemylabs** [comment] 2022-02-23 20:33
@helto4real yes, it is stilll retrying setup: None even after reinstallation.

**Comment by helto4real** [comment] 2022-03-04 15:59
If someone could try with the latest version. I hope everything should be fixed now. I managed to at least reproduce and make it work :)

**Closed as completed** 2022-07-05 05:23 UTC
